"use strict";
var matz = new matrizdispersa();
matz.insertar('test3', 5, 4);
matz.insertar('test', 1, 1);
matz.insertar('test2', 3, 2);
matz.insertar('test4', 1, 3);
matz.insertar('test3', 2, 4);
matz.recorrerfilas();
console.log("Recorrido por Columa");
matz.recorrercolumna();
